import { test } from '@japa/runner'
import { definitionContent, javascriptContent } from '../src/generate_routes.js'
import { type SerializedRoute } from '../src/types/manifest.js'

function cs(s: string) {
  return s.replace(/ /g, '').replace(/\t/g, '').replace(/\n/g, '')
}

test.group('definitionContent', () => {
  test('should generate definition content correctly without params', ({ assert }) => {
    const bucket = [
      {
        name: 'home',
        path: '/home',
        method: 'get',
        domain: 'root',
      },
      {
        name: 'user',
        path: '/users/:id',
        method: 'get',
        params: { required: ['id'] },
        domain: 'root',
      },
    ] as SerializedRoute[]

    const expectedDefinitionContent = `// Generated automatically by @izzyjs/route
// Do not modify this file
declare module '@izzyjs/route/routes' {
\tinterface RouteDefinitions {
\t\t'home': {
\t\t\treadonly name: 'home';
\t\t\treadonly path: '/home';
\t\t\treadonly method: 'get';
\t\t\treadonly domain: 'root';
\t\t};
\t\t'user': {
\t\t\treadonly name: 'user';
\t\t\treadonly path: '/users/:id';
\t\t\treadonly method: 'get';
\t\t\treadonly params: {
\t\t\t\treadonly required: readonly ['id'];
\t\t\t};
\t\t\treadonly domain: 'root';
\t\t};
\t}
}`

    const generatedDefinitionContent = definitionContent(bucket)

    assert.equal(cs(generatedDefinitionContent), cs(expectedDefinitionContent))
  })

  test('should generate definition content correctly with params', ({ assert }) => {
    const bucket = [
      {
        name: 'home',
        path: '/home',
        method: 'get',
        domain: 'root',
      },
    ] as SerializedRoute[]

    const expectedDefinitionContent = `// Generated automatically by @izzyjs/route
// Do not modify this file
declare module '@izzyjs/route/routes' {
\tinterface RouteDefinitions {
\t\t'home': {
\t\t\treadonly name: 'home';
\t\t\treadonly path: '/home';
\t\t\treadonly method: 'get';
\t\t\treadonly domain: 'root';
\t\t};
\t}
}`

    const generatedDefinitionContent = definitionContent(bucket)

    assert.equal(cs(generatedDefinitionContent), cs(expectedDefinitionContent))
  })
})

test.group('javascriptContent', () => {
  test('should generate javascript content correctly', ({ assert }) => {
    const bucket = [
      {
        name: 'home',
        path: '/home',
        method: 'get',
        domain: 'root',
      },
      {
        name: 'user',
        path: '/users/:id',
        method: 'get',
        params: { required: ['id'] },
        domain: 'root',
      },
    ] as SerializedRoute[]

    const expectedJavascriptContent = `/* eslint-disable prettier/prettier */
// Generated automatically by named routes hook
/* DO NOT EDIT THIS FILE DIRECTLY */

export const routes = [
	{
		"name": "home",
		"path": "/home",
		"method": "get",
		"domain": "root"
	},
	{
		"name": "user",
		"path": "/users/:id",
		"method": "get",
		"params": {
			"required": ["id"]
		},
		"domain": "root"
	}
];`

    const generatedJavascriptContent = javascriptContent(bucket)

    assert.equal(cs(generatedJavascriptContent), cs(expectedJavascriptContent))
  })

  test('should generate definition content correctly with optional parameters', async ({
    assert,
  }) => {
    const bucket = [
      {
        name: 'posts.show',
        path: '/posts/:id/:slug?',
        method: 'get',
        params: {
          required: ['id'],
          optional: ['slug'],
        },
        domain: 'root',
      },
    ] as SerializedRoute[]

    const expectedDefinitionContent = `// Generated automatically by @izzyjs/route
// Do not modify this file
declare module '@izzyjs/route/routes' {
\tinterface RouteDefinitions {
\t\t'posts.show': {
\t\t\treadonly name: 'posts.show';
\t\t\treadonly path: '/posts/:id/:slug?';
\t\t\treadonly method: 'get';
\t\t\treadonly params: {
\t\t\t\treadonly required: readonly ['id'];
\t\t\t\treadonly optional: readonly ['slug'];
\t\t\t};
\t\t\treadonly domain: 'root';
\t\t};
\t}
}`

    const generatedDefinitionContent = definitionContent(bucket)

    assert.equal(cs(generatedDefinitionContent), cs(expectedDefinitionContent))
  })

  test('should generate definition content correctly with only optional parameters', async ({
    assert,
  }) => {
    const bucket = [
      {
        name: 'posts.index',
        path: '/posts/:category?',
        method: 'get',
        params: {
          optional: ['category'],
        },
        domain: 'root',
      },
    ] as SerializedRoute[]

    const expectedDefinitionContent = `// Generated automatically by @izzyjs/route
// Do not modify this file
declare module '@izzyjs/route/routes' {
\tinterface RouteDefinitions {
\t\t'posts.index': {
\t\t\treadonly name: 'posts.index';
\t\t\treadonly path: '/posts/:category?';
\t\t\treadonly method: 'get';
\t\t\treadonly params: {
\t\t\t\treadonly optional: readonly ['category'];
\t\t\t};
\t\t\treadonly domain: 'root';
\t\t};
\t}
}`

    const generatedDefinitionContent = definitionContent(bucket)

    assert.equal(cs(generatedDefinitionContent), cs(expectedDefinitionContent))
  })

  test('should generate javascript content correctly with optional parameters', async ({
    assert,
  }) => {
    const bucket = [
      {
        name: 'posts.show',
        path: '/posts/:id/:slug?',
        method: 'get',
        params: {
          required: ['id'],
          optional: ['slug'],
        },
        domain: 'root',
      },
    ] as SerializedRoute[]

    const expectedJavascriptContent = `/* eslint-disable prettier/prettier */
// Generated automatically by named routes hook
/* DO NOT EDIT THIS FILE DIRECTLY */

export const routes = [
	{
		"name": "posts.show",
		"path": "/posts/:id/:slug?",
		"method": "get",
		"params": {
			"required": ["id"],
			"optional": ["slug"]
		},
		"domain": "root"
	}
];`

    const generatedJavascriptContent = javascriptContent(bucket)

    assert.equal(cs(generatedJavascriptContent), cs(expectedJavascriptContent))
  })
})
