import { test } from '@japa/runner'
import { definitionContent, javascriptContent } from '../src/generate_routes.js'
import { SerializedRoute } from '../src/types/manifest.js'

function cs(s: string) {
  return s.replace(/ /g, '').replace(/\t/g, '').replace(/\n/g, '')
}

test.group('definitionContent', () => {
  test('should generate definition content correctly without params', ({ assert }) => {
    const bucket = [
      {
        name: 'home',
        path: '/home',
        method: 'get',
      },
      {
        name: 'user',
        path: '/users/:id',
        method: 'get',
        params: ['id'],
      },
    ] as SerializedRoute[]

    const expectedDefinitionContent = `// Generated automatically by @bise/route
// Do not modify this file

export declare const routes: readonly [
  {
    readonly name: 'home';
    readonly path: '/home';
    readonly method: 'get';
  },
  {
    readonly name: 'user';
    readonly path: '/users/:id';
    readonly method: 'get';
    readonly params: readonly ['id'];
  }
];
export type Routes = typeof routes;
export type Route = Routes[number];
export type RouteWithName = Extract<Route, { name: string }>;
export type RouteWithParams = Extract<Route, { params: ReadonlyArray<string>; }>;
export type RouteName = Exclude<RouteWithName['name'], ''>;`

    const generatedDefinitionContent = definitionContent(bucket)

    assert.equal(cs(generatedDefinitionContent), cs(expectedDefinitionContent))
  })

  test('should generate definition content correctly with params', ({ assert }) => {
    const bucket = [
      {
        name: 'home',
        path: '/home',
        method: 'get',
      },
    ] as SerializedRoute[]

    const expectedDefinitionContent = `// Generated automatically by @bise/route
// Do not modify this file
export declare const routes: readonly [
\t{
\t\treadonly name: 'home';
\t\treadonly path: '/home';
\t\treadonly method: 'get';
\t}
];
export type Routes = typeof routes;
export type Route = Routes[number];
export type RouteWithName = Extract<Route, { name: string }>;
export type RouteWithParams = Extract<Route, { params: ReadonlyArray<string>; }>;
export type RouteName = Exclude<RouteWithName['name'], ''>;`

    const generatedDefinitionContent = definitionContent(bucket)

    assert.equal(cs(generatedDefinitionContent), cs(expectedDefinitionContent))
  })
})

test.group('javascriptContent', () => {
  test('should generate javascript content correctly', ({ assert }) => {
    const bucket = [
      {
        name: 'home',
        path: '/home',
        method: 'get',
      },
      {
        name: 'user',
        path: '/users/:id',
        method: 'get',
        params: ['id'],
      },
    ] as SerializedRoute[]

    const expectedJavascriptContent = `/* eslint-disable prettier/prettier */
// Generated automatically by named routes hook
/* DO NOT EDIT THIS FILE DIRECTLY */
export const routes = [
	{
		"name": "home",
		"path": "/home",
		"method": "get"
	},
	{
		"name": "user",
		"path": "/users/:id",
		"method": "get",
		"params": ["id"]
	}
];`

    const generatedJavascriptContent = javascriptContent(bucket)

    assert.equal(cs(generatedJavascriptContent), cs(expectedJavascriptContent))
  })
})
